### ISSUE TITLE
Ergo: User Interface new component

### ISSUE THREAD

**Issue by sergiotejon** [freepik-company/fc-py-inferia#109]
#### Description
We propose adding a new component called `ergo componente` to the Cogito core to facilitate the auto-generation of user interfaces. This new component will streamline the process of creating user interfaces for various applications within Cogito.

#### Implementation
To implement this feature, we will introduce a new `ergo.user_interface` dictionary in the `cogito.yaml` configuration file. This dictionary will allow users to configure the user interface generation component with their preferred tools.

#### Examples of Tools
- **NiceGUI**: A tool for creating web-based user interfaces with Python.
- **Gradio**: A tool for creating user interfaces for machine learning models.

#### Example: Using NiceGUI
```yaml
cogito:
  predictor: predict:Predictor
  server:
    cache_dir: /tmp/cogito
    description: Inference server
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    readiness_file: /tmp/cogito-readiness.lock
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      tags:
      - predict
    threads: 4
    version: 0.1.0
  trainer: 'train:Trainer'
  ergo:
    user_interface:
      tool: NiceGUI
      config:
        theme: light
        port: 8080
config_version: 1
```

#### Example: Using Gradio
```yaml
cogito:
  predictor: predict:Predictor
  server:
    cache_dir: /tmp/cogito
    description: Inference server
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    readiness_file: /tmp/cogito-readiness.lock
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      tags:
      - predict
    threads: 4
    version: 0.1.0
  trainer: 'train:Trainer'
  ergo:
    user_interface:
      tool: Gradio
      config:
        theme: dark
        port: 7860
config_version: 1
```

### Review and Submission
Please review the above description and examples to ensure they meet the requirements for the new component. Once reviewed, submit the issue on the GitHub repository to request the addition of the `ergo componente` to the Cogito core.
