### ISSUE TITLE
Feature Request: Add New Component (Ergo Component) to Deploy cogito in a Kubernetes Cluster

### ISSUE THREAD

**Issue by sergiotejon** [freepik-company/fc-py-inferia#110]
### Description
We propose adding a new component called Ergo Component to facilitate the deployment of Cogito in a Kubernetes cluster. This component will streamline the deployment process and ensure that Cogito can be easily scaled and managed within a Kubernetes environment.

### Why This Feature is Needed
Scalability: Kubernetes allows for horizontal scaling of applications, which is essential for handling increased loads.
Management: Kubernetes provides robust tools for managing containerized applications, making it easier to deploy, update, and monitor Cogito.
Portability: Kubernetes ensures that Cogito can run consistently across different environments, from local development to production.
Benefits and Impact
Improved Deployment Process: Automated deployment scripts and configurations will simplify the deployment of Cogito.
Enhanced Reliability: Kubernetes' self-healing capabilities will improve the reliability and availability of Cogito.
Resource Efficiency: Kubernetes can optimize resource usage, leading to more efficient operation of Cogito.
Examples and Use Cases
Example 1: Automated Deployment: Using Helm charts to deploy Cogito with a single command.
Example 2: Scaling: Automatically scaling Cogito instances based on traffic and load.
Example 3: Monitoring and Logging: Integrating with Kubernetes-native monitoring and logging tools for better observability.
### Review and Submission
Please review the above description to ensure it meets the requirements for the new component. Once reviewed, submit the issue on the GitHub repository to request the addition of the Ergo Component for deploying Cogito in a Kubernetes cluster.

Here's an example configuration for the `ergo.disponendum` component in the `cogito.yaml` file:

```yaml
cogito:
  predictor: predict:Predictor
  server:
    cache_dir: /tmp/cogito
    description: Inference server
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    readiness_file: /tmp/cogito-readiness.lock
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      tags:
      - predict
    threads: 4
    version: 0.1.0
  trainer: train:Trainer
  ergo:
    disponendum:
      k8s_contexts: [ X, Y, Z]
      config:
        replicas: X
        namespace: XXX
        ...
config_version: 1
```

You can adjust the `tool` and `config` values to use different tools or configurations as needed.
